name: MacOS

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
          # go-version: 1.22.6
          go-version: 1.19.13
      - name: fyne install
        run: go install fyne.io/fyne/v2/cmd/fyne@v2.5.1
      - name: fyne build
        run: |
          fyne package -os darwin -icon icon.png
          zip -r loadsimulator.zip loadsimulator.app
          ls

      # - name: create-dmg-action
      #   # You may pin to the exact commit or the version.
      #   # uses: QQxiaoming/create-dmg-action@9da339e5d8baa50036b55ed2c6545fb51cee72c4
      #   uses: QQxiaoming/create-dmg-action@v0.0.2
      #   with:
      #     # source dir
      #     srcdir: loadsimulator.app
      #     # dmg name
      #     name: loadsimulator
                
      - name: Release Upload
        # You may pin to the exact commit or the version.
        # uses: d1ceward/draft-assets-release-action@11f2da8927596ab5de9885b323c3a035fc6a2107
        uses: d1ceward/draft-assets-release-action@v3.0.0
        with:
          # The GitHub access token which will be used to upload release artifacts. Usually this will be `secrets.GITHUB_TOKEN`.
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            loadsimulator.zip
          # A list of files to publish, relative to the repository root.The files must be specified as a newline-delimited list of paths.